### ISSUE TITLE
add the FIT logo to MTF's sponsor page

### ISSUE THREAD

**Issue by svpernova09** [memtech/memphistechnology.org#103]
Add FIT
Remove Rocketfuel

Files to be changed:

* https://github.com/memtech/memphistechnology.org/blob/master/source/about/sponsors.html.twig#L26-L30
* Create a FIT logo file in this folder: https://github.com/memtech/memphistechnology.org/tree/master/source/components/img
  * Logo Attached, Maybe rename to `fit-logo.png`?
* Link to `http://www.memphis.edu/fedex`
* Description text: `The FedEx Institute of Technology is an advanced research institution dedicated to connecting and building up the Memphis tech community`

![UofM_hex_cmyk_FIT _updated color code_orange](https://user-images.githubusercontent.com/967362/100273159-fa052700-2f21-11eb-8b17-f78a9d60646c.png)

![image](https://user-images.githubusercontent.com/967362/100272164-464f6780-2f20-11eb-9667-6f346c856dfc.png)

**Comment by Capocaccia** [comment]
Ive got this one.  Ill have a PR in this weekend.

**Comment by Capocaccia** [comment]
PR here:

https://github.com/memtech/memphistechnology.org/pull/104
