### ISSUE TITLE
Add calls to action to the website for new posts and code contributions

### ISSUE THREAD

**Issue by dpritchett** [memtech/memphistechnology.org#11]
Not to say that you should actually be *accepting* surprise blog posts submitted by randos on PRs.

But!  I go to the site and I don't immediately grok that it's driven by a github repo that I could conceivably add code to.

@brob - UX ideas here?  I wouldn't mind a FORK THIS ON GITHUB ribbon but maybe you have classier ideas.

![image](https://cloud.githubusercontent.com/assets/147981/7612876/1023939c-f953-11e4-959c-8b0a205745b9.png)

**Comment by bradmontgomery** [comment]
In my experience, people flooding you with free blog posts is a non-existing problem.

**Comment by dpritchett** [comment]
:laughing: 

Let's close this and open a RFC issue on web-based feedback and communication opportunities.
