### ISSUE TITLE
Request for comments - How can MTF solicit constructive feedback and contributions via the web?

### ISSUE THREAD

**Issue by dpritchett** [memtech/memphistechnology.org#14]
# Spitballed ideas

- A FAQ page
- A suggestions forum
- A this-is-how-MTF-operates-and-here-is-how-you-can-help guide

**Comment by dpritchett** [comment]
@bradmontgomery and I were discussing the pros and cons of gittip's attempt at radical transparency.  IIRC they published all their financials online and solicited feedback on the business model and operations via Github.  Things went ok until [some sort of geek feminism flameout](http://geekfeminism.wikia.com/wiki/Gittip_crisis).

**Comment by dpritchett** [comment]
cc @joshwlewis

**Comment by sanseref** [comment]
Like any organization, for feedback, I think going to the meetings and sending emails to a board member would work. But something in the About Us section of their website (or an FAQ page) would be great to let the community know how MTF can help and what to do to get support from them.

**Comment by dpritchett** [comment]
@sanseref I would like to see more public dialogue.  Not everyone's gonna make it to a board meeting, and not everyone can read board member email.  This is a pretty neat venue for conversations, honestly.

**Comment by dpritchett** [comment]
Good news everyone, I found Pandora's box!

![image](https://cloud.githubusercontent.com/assets/147981/7616539/c32a16d4-f96a-11e4-85a5-8592a2350fd3.png)

**Comment by svpernova09** [comment]
I would suggest a MTF Google Group (We have one, but it's not very aptly named and board only atm. We could possibly rename and open it up) to house these types of conversations.

**Comment by dpritchett** [comment]
As long as there's a public, easily reviewed channel of communication
that's clearly called out on the MTF website I think you'll save a lot of
headaches.  Google Group sounds fine to me... assuming Github issues aren't
the right place for things that aren't the website.

**Comment by svpernova09** [comment]
https://groups.google.com/forum/#!forum/memphis-technology

Everyone should be able to see that, and see the threads / content. But you will have to request to join to post there.
