### ISSUE TITLE
Revisiting the Past: Mentoring Office Hours

### ISSUE THREAD

**Issue by unijohn** [memtech/memphistechnology.org#73]
1. What is the history with this MTF item?  
2. Are we still open to do it?  Are we still doing it in some capacity outside of Slack and/or meetups?

Source: [Recap Mentoring Office Hours](http://www.memphistechnology.org/meetings/4-21-15-agenda/)

**Comment by svpernova09** [comment]
Same as https://github.com/memtech/memphistechnology.org/issues/77#issuecomment-399766130
