### ISSUE TITLE
Board Members page

### ISSUE THREAD

**Issue by bradmontgomery** [memtech/memphistechnology.org#8]
Need a page with all the board members, a bio, and their mugshots.

**Comment by svpernova09** [comment]
TODO:

* mugshots

I'd like to tie into gravatar, but there is no sculpin thing to do it, so we'd have to write that. And .... yeah. I dunno, static images may be fine.

**Comment by bradmontgomery** [comment]
I can make gravatar mugshots work without any code!

**Comment by bradmontgomery** [comment]
I'm gonna call this issue closed. Linking to a static image or manually including someone's gravatar is _good enough_.
