### ISSUE TITLE
Publish Minutes?

### ISSUE THREAD

**Issue by bradmontgomery** [memtech/memphistechnology.org#9]
Should we publish meeting minutes on the site?

**Comment by svpernova09** [comment]
Yes we should. It would be very trivial to do so.

**Comment by bradmontgomery** [comment]
:+1: @brob you're doing minutes right?  Make sure I have a link and I'll make them web-friendly.

**Comment by bradmontgomery** [comment]
or @svpernova09 will. that's cool, too.

**Comment by svpernova09** [comment]
All meetings I have (that we have in our Google docs folder) have been published to http://www.memphistechnology.org/meetings/

**Comment by dpritchett** [comment]
This is awesome, thanks so much.
